# -*- coding: utf-8 -*-
"""Kmeans Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oknE4D7KjH_tjNDXdScGhaC6Ioso_pn6
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

plt.rcParams['figure.figsize'] = (10, 6)
sns.set_style('whitegrid')
print('All libraries loaded!')

df = pd.read_csv('clean_data.csv')
print(f'Shape: {df.shape}')
df.head(10)

print('Null values:')
print(df.isnull().sum())
print()
print('Data types:')
print(df.dtypes)
print()
df.describe()

# --- 3a. Salary midpoint ---
df['sal_low']    = df['salary_usd'].str.split('-').str[0].astype(int)
df['sal_high']   = df['salary_usd'].str.split('-').str[1].astype(int)
df['salary_mid'] = (df['sal_low'] + df['sal_high']) / 2

print('Salary midpoint stats:')
print(df['salary_mid'].describe())

# --- 3b. Label encode job_title and location ---
le = LabelEncoder()
df['job_title_enc'] = le.fit_transform(df['job_title'].str.strip().str.title())
df['location_enc']  = le.fit_transform(df['location'].str.strip())

print('Job title encoding:')
print(df[['job_title', 'job_title_enc']].drop_duplicates().sort_values('job_title_enc'))

# --- 3c. Location cost-of-living multiplier (from the data generator) ---
LOCATION_MULTIPLIER = {
    'San Francisco, Ca': 1.20,
    'New York, Ny':      1.15,
    'Seattle, Wa':       1.10,
    'Boston, Ma':        1.08,
    'Chicago, Il':       1.05,
    'Remote':            1.02,
    'Austin, Tx':        1.00,
}
df['location_clean'] = df['location'].str.strip().str.title()
df['loc_multiplier'] = df['location_clean'].map(LOCATION_MULTIPLIER).fillna(1.0)
print('Location multipliers applied:')
print(df[['location_clean', 'loc_multiplier']].drop_duplicates())

# --- 3d. Skill binary flags ---
ALL_SKILLS = ['Python', 'SQL', 'Tableau', 'Power BI', 'AWS',
              'Spark', 'Pandas', 'TensorFlow', 'Airflow', 'dbt']

for skill in ALL_SKILLS:
    col = f'skill_{skill.lower().replace(" ", "_")}'
    df[col] = df['skills'].str.contains(skill, case=False, na=False).astype(int)

skill_cols = [f'skill_{s.lower().replace(" ", "_")}' for s in ALL_SKILLS]
print('Skill flags (first 5 rows):')
df[['skills'] + skill_cols].head()

# --- 3e. Assemble the final feature matrix ---
FEATURE_COLS = [
    'salary_mid',
    'years_experience',
    'job_title_enc',
    'loc_multiplier',
]

X = df[FEATURE_COLS].copy()
print(f'Feature matrix shape: {X.shape}')
X.head()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print('Scaled feature matrix shape:', X_scaled.shape)
print('Mean (should be ~0):', X_scaled.mean(axis=0).round(4))
print('Std  (should be ~1):', X_scaled.std(axis=0).round(4))

K_RANGE = range(2, 11)
inertias    = []
silhouettes = []

for k in K_RANGE:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_scaled)
    inertias.append(km.inertia_)
    silhouettes.append(silhouette_score(X_scaled, labels))
    print(f'k={k}  inertia={km.inertia_:.0f}  silhouette={silhouettes[-1]:.4f}')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Elbow plot
axes[0].plot(list(K_RANGE), inertias, 'bo-', linewidth=2, markersize=8)
axes[0].set_title('Elbow Method — Inertia vs K', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Number of Clusters (K)')
axes[0].set_ylabel('Inertia (Within-cluster sum of squares)')
axes[0].set_xticks(list(K_RANGE))

# Silhouette plot
axes[1].plot(list(K_RANGE), silhouettes, 'rs-', linewidth=2, markersize=8)
axes[1].set_title('Silhouette Score vs K', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Number of Clusters (K)')
axes[1].set_ylabel('Silhouette Score (higher = better)')
axes[1].set_xticks(list(K_RANGE))

best_k = list(K_RANGE)[silhouettes.index(max(silhouettes))]
axes[1].axvline(x=best_k, color='green', linestyle='--', label=f'Best K = {best_k}')
axes[1].legend()

plt.tight_layout()
plt.savefig('elbow_silhouette.png', dpi=150, bbox_inches='tight')
plt.show()
print(f'\nBest K by silhouette: {best_k}')

BEST_K = best_k   # change this if you want to try a different K

kmeans = KMeans(n_clusters=BEST_K, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(X_scaled)

print(f'K-Means fitted with K = {BEST_K}')
print()
print('Cluster sizes:')
print(df['cluster'].value_counts().sort_index())

pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

explained = pca.explained_variance_ratio_
print(f'Variance explained — PC1: {explained[0]:.1%}, PC2: {explained[1]:.1%}, Total: {sum(explained):.1%}')

pca_df = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])
pca_df['cluster'] = df['cluster'].values

palette = sns.color_palette('tab10', BEST_K)

plt.figure(figsize=(10, 7))
for c in range(BEST_K):
    mask = pca_df['cluster'] == c
    plt.scatter(pca_df.loc[mask, 'PC1'], pca_df.loc[mask, 'PC2'],
                color=palette[c], alpha=0.5, s=20, label=f'Cluster {c}')

# Plot centroids in PCA space
centroids_pca = pca.transform(kmeans.cluster_centers_)
plt.scatter(centroids_pca[:, 0], centroids_pca[:, 1],
            c='black', marker='X', s=200, zorder=5, label='Centroids')

plt.title(f'K-Means Clusters (K={BEST_K}) — PCA Projection', fontsize=14, fontweight='bold')
plt.xlabel(f'PC1 ({explained[0]:.1%} variance)')
plt.ylabel(f'PC2 ({explained[1]:.1%} variance)')
plt.legend()
plt.tight_layout()
plt.savefig('clusters_pca.png', dpi=150, bbox_inches='tight')
plt.show()

# Numeric summary per cluster
summary = df.groupby('cluster')[['salary_mid', 'years_experience']].mean().round(0)
summary['count'] = df['cluster'].value_counts().sort_index()
print('Cluster numeric summary:')
print(summary)

# Most common job title and location per cluster
for c in range(BEST_K):
    subset = df[df['cluster'] == c]
    top_title    = subset['job_title'].mode()[0]
    top_location = subset['location'].mode()[0]
    avg_salary   = subset['salary_mid'].mean()
    avg_exp      = subset['years_experience'].mean()
    top_skills   = subset[skill_cols].mean().sort_values(ascending=False).head(3).index.tolist()
    top_skills   = [s.replace('skill_', '').replace('_', ' ').title() for s in top_skills]
    print(f'Cluster {c} ({len(subset)} jobs):')
    print(f'  Avg salary    : ${avg_salary:,.0f}')
    print(f'  Avg experience: {avg_exp:.1f} years')
    print(f'  Top job title : {top_title}')
    print(f'  Top location  : {top_location}')
    print(f'  Top 3 skills  : {top_skills}')
    print()

# Heatmap: average skill presence per cluster
skill_heatmap = df.groupby('cluster')[skill_cols].mean()
skill_heatmap.columns = [c.replace('skill_', '').replace('_', ' ').title() for c in skill_heatmap.columns]

plt.figure(figsize=(12, 5))
sns.heatmap(skill_heatmap, annot=True, fmt='.2f', cmap='YlOrRd',
            linewidths=0.5, cbar_kws={'label': 'Avg presence (0-1)'})
plt.title('Average Skill Presence per Cluster', fontsize=14, fontweight='bold')
plt.ylabel('Cluster')
plt.tight_layout()
plt.savefig('skill_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# Salary distribution per cluster
plt.figure(figsize=(10, 6))
for c in range(BEST_K):
    subset = df[df['cluster'] == c]['salary_mid']
    sns.kdeplot(subset, label=f'Cluster {c}', fill=True, alpha=0.3)

plt.title('Salary Distribution per Cluster', fontsize=14, fontweight='bold')
plt.xlabel('Salary Midpoint (USD)')
plt.ylabel('Density')
plt.legend()
plt.tight_layout()
plt.savefig('salary_distribution.png', dpi=150, bbox_inches='tight')
plt.show()

# Experience vs Salary scatter coloured by cluster
plt.figure(figsize=(10, 7))
for c in range(BEST_K):
    mask = df['cluster'] == c
    plt.scatter(df.loc[mask, 'years_experience'],
                df.loc[mask, 'salary_mid'],
                color=palette[c], alpha=0.4, s=20, label=f'Cluster {c}')

plt.title('Experience vs Salary by Cluster', fontsize=14, fontweight='bold')
plt.xlabel('Years of Experience')
plt.ylabel('Salary Midpoint (USD)')
plt.legend()
plt.tight_layout()
plt.savefig('exp_vs_salary.png', dpi=150, bbox_inches='tight')
plt.show()

